### PR TITLE
Removed old list item counter, replaced with check-icon and functiona…

### PR DESCRIPTION
**Pull request by jacobselg**
Reused icon 'ic_action_done_before' and 'ic_action_done_after', too small?

### CODE REVIEW

**Comment by ghost** [comment]
Should save to json file when click on button!

**Comment by jacobselg** [comment]
Affirmative, refactoring in progress.

**Comment by jacobselg** [comment]
Refactored, ready for merge.

**Comment by LinneaMalcherek** [comment]
Really well written code. This is sooo awesome, I can't almost believe it! :D :D :dancer: :rabbit: :tada:

**Comment by jacobselg** [comment]
Thanks! :rabbit:

**Pull request merged**
